
@api = http://localhost:4000/pacientes
###
GET {{api}}
###
POST {{api}}
Content-Type: application/json 

{
    "pacient": 
{
    "firstName": "Rodrigo",
    "lastName": "Diaz",
    "email": "alsdte@gilmail.com",
    "dni": "55555355",
    "cell": "1132459658"
}
}
###
GET {{api}}/1