
@api = http://localhost:4000/pacientes
###
GET {{api}}
###
POST {{api}}
Content-Type: application/json 

{
    "paciente": 
{
    "firstName": "",
    "lastName": "Sorete",
    "email": "alsorete@gilmail.com",
    "dni": 95874651,
    "cell": 1124589658
}
}